title: <p align="center"> Ambily M </p>
logo: /assets/img/Ambily.jpg
description: Working as R&D Specialist in NOKIA with 11+ years of IT experience in Bigdata, Hadoop, Spark, PySpark, Hive, MongoDB, Business Intelligence, Data warehousing, Python. 
1 year experience in AI/ML usecases like Subscriber Clustering, Subscriber Churn and ML pipeline building. 
theme: jekyll-theme-minimal
